baseURL = 'https://dennisxie.github.io.org/'
languageCode = 'en-us'
title = "Dennis's Grocery"
theme = "hugo-papermod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
